### ISSUE TITLE
Expecting property name: line 1 column 2 (char 1)

### ISSUE THREAD

**Issue by abunsen** [igorgue/pjson#16]
https://gist.github.com/abunsen/72416c68d9ac73d6fba9 as test.json

and then `cat test.json | pjson` yields `Expecting property name: line 1 column 2 (char 1)`

**Comment by winny-** [comment]
That is invalid JSON. JSON strings must start and end with a double quote (`"`).

More information on [json.org](http://json.org/).

**Comment by igorgue** [comment]
I wonder if I could just support JavaScript and that would solve this? I like this tool to tell me my JSON is correct or incorrect though. It saved my ass a couple of times already.

**Comment by abunsen** [comment]
@winny- thank you.
