### ISSUE TITLE
How can I pipe to less or more?

### ISSUE THREAD

**Issue by ccbcreg** [igorgue/pjson#2]
I create some rather large json files and would like to pass or pipe the output from pjson to programs like less or more.  However, I am not getting the desired results, see example below.  Could you suggest a way to do this?

This works great!:

	echo test.js | pjson 

	{
	  "australia": {
	    "iso": "AU", 
	    "name": "Australia"
	  }
	}

I'd like to be able to pass the output from pjson to less or more like so:

	echo test.js | pjson | less

	{ESC[39;49;00m
	  ESC[39;49;00mESC[34;01m"australia"ESC[39;49;00m:ESC[39;49;00m ESC[39;49;00m{ESC[39;49;00m
	    ESC[39;49;00mESC[34;01m"iso"ESC[39;49;00m:ESC[39;49;00m ESC[39;49;00mESC[33m"AU"ESC[39;49;00m,ESC[39;49;00m ESC[39;49;00m
	    ESC[39;49;00mESC[34;01m"name"ESC[39;49;00m:ESC[39;49;00m ESC[39;49;00mESC[33m"Australia"ESC[39;49;00m
	  ESC[39;49;00m}ESC[39;49;00m
	}ESC[39;49;00m

Any suggestions?

**Comment by aerovistae** [comment]
Didn't work for me :( got the formatting but no color.

**Comment by igorgue** [comment]
@aerovistae Did a little bit of research and I'm not sure how to fix the issue. Does `less` prints in color?

**Comment by winny-** [comment]
This might be of interest -- https://github.com/alghanmi/terminal_color_test -- pipe this through less, with the appropriate flags set -- `-R`, I think?

**Comment by igorgue** [comment]
@winny- interesting, wonder if there's an option in Pygments to do that, looking at the code here, looks to me I need to use the `format` function directly, I wonder if I upgrade Pygments it'll work out, anyways, I'll take a look later, here's the piece of the code I think is where I gonna have to do something else: https://bitbucket.org/birkenfeld/pygments-main/src/a287342ee7165f50fdd54e3500be48256222cff6/pygments/__init__.py?at=default#cl-79

**Comment by winny-** [comment]
@igorgue Oh, no. I only mentioned [alghanmi/terminal_color_test](https://github.com/alghanmi/terminal_color_test) to demonstrate an easy way to make sure color is working properly.

As mentioned earlier, color can be enabled via passing the `-t` flag to `pjson` in conjunction to the `-R` flag for `less`. Example:

![screen shot 2015-05-26 at 20 34 37](https://cloud.githubusercontent.com/assets/3893828/7826946/accef8e2-03e6-11e5-9bc5-46c91262dcce.png)

**Comment by igorgue** [comment]
Ahh @winny- got it, thanks!
